namespace LoadTester;

public static class RandomGenerator
{
    private static readonly string[] Churches = new []
    {
        "Adjud",
"A-lag Brunstad",
"A-lag MOBILT",
"Beljaevka",
"Bergen",
"Bucharest",
"Connecticut",
"Crasna",
"Didcot",
"Drammen Sande",
"Dürrmenz",
"Eiker",
"Exter",
"Fulda",
"Gelderland",
"Graz",
"Grenland",
"Groningen",
"Hallingdal",
"Hamar",
"Hamburg",
"Harstad",
"Hessenhöfe",
"Holstebro",
"Hønefoss",
"Horten",
"Huntworth",
"København",
"Lahti",
"Lilienhof",
"Linnenbach",
"Malinka",
"Måløy",
"Maubach",
"Melbourne",
"Mittewald",
"Molde",
"Nancy",
"Novo Sarandi",
"Oslo og Follo",
"Østfold",
"Ottawa",
"Ozornoe",
"Para",
"Raumberg",
"Sandefjord",
"Schweiz",
"Seattle",
"Shanghai",
"Singapore",
"Sørlandet",
"South Africa",
"Stavanger",
"Stord",
"St. Petersburg",
"Ternopol",
"Tønsberg",
"Twente",
"Vácduka",
"Valdres",
"Vancouver",
"Waldhausen",
"Waltrop",
"West-Nederland",
"Wien",
"Winnipeg",
"Wroclaw",
"Zakarpattia",
    };

    private static readonly string[] Prefixes = new[]
    {
        "Fet",
        "Gjes",
        "Høy",
        "Inn",
        "Fager",
        "Lille",
        "Lo",
        "Mal",
        "Nord",
        "Nær",
        "Sand",
        "Sme",
        "Stav",
        "Stor",
        "Tand",
        "Ut",
        "Vest",
        "Ber",
        "Tøn",
        "Har",
        "Tor",
        "Kristian",
        "Aren",
        "Joste",
        "Viks",
        "Nøtter",
        "Hell",
        "Geir",
        "Li",
        "Skarp",
        "Mel",
        "Øst",
        "Vest",
        "Ski",
        "Elve",
        "Eik",
    };

    public static string Church()
    {
        return Churches[Random.Shared.Next(Churches.Length)];
    }

    public static string TeamName()
    {
        return Guid.NewGuid().ToString();
    }
}